# Generated by Django 4.0.5 on 2022-06-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroundMe', '0002_auto_20211004_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitud',
            field=models.FloatField(default=-33.5947),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitud',
            field=models.FloatField(default=-71.6075),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hola, AroundMe', max_length=100),
        ),
    ]
